### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by dbernheisel** [vigetlabs/elixir-deploy-quickstart#1]
cc @yaychris @zporter

**Comment by zporter** [comment]
Initial scan revealed some Phoenix / Ecto specific stuff in the Secrets section. Might be worth mentioning "if your app uses Ecto, then you'll need to set these secrets", etc.

**Comment by yaychris** [comment]
Looks great overall. A few comments:

1. It's best (required, really) practice in shell scripts to _always_ have quotes around variables. There are lots of bugs that can pop up when you don't—for example, `cd $APP` will fail if the path stored in `$APP` has spaces in it.

2. I really like using environment variables for config vars. However, I don't think `~/.bashrc` is the right place for them. Since they're exported, any command started by a shell with that file sourced will see your secrets.

    A better approach would be to move them to an app-specific environment file that gets loaded when the app starts up. Unfortunately, it's not easy to do this with Distillery. For C2C, I wrote a plugin that overwrites the built-in `boot_check` startup script with one that sources the environment file. You can check that out [here](https://github.com/C2CPII/audit-app/tree/master/rel).

3. Not a problem with what you've posted, but I ran into an issue where I couldn't run two versions of the app (`integration` and `staging`) on the same server, because Distillery's `vm.args` file hardcodes the Erlang node name to the app's name, and it doesn't work because the node names must be unique. That's also addressed in the code linked above. Just thought I'd share.

**Comment by dbernheisel** [comment]
Good point @zporter. I'll leave a comment about ecto being optional in some projects.

Thanks @yaychris, that stuff looks great!

1. Yep, agree. Looks like I missed the double-quoting in a script. I'll correct that.
2. Dope. This is great. I ran into this too and had secrets in a `env.prod` file and had systemd source it automatically with `EnvironmentFile=/home/deploy/your_app/env.prod`, but that didn't work when running commands (like migrate) during deploy. To avoid secrets in `.bashrc`, do you think the following would be better?:

    ```bash
    for secret in "$RELEASE_ROOT_DIR"/env.prod; do
      export "$secret"
    done
    ```

    then this could live in `migrate.sh` script that distillery uses, and any other command.

    Your plugin solution is slicker, but it looks like it might require the secrets to be in the build environment, and limits any use of run-time configurations. I also hesitate with a distillery plugin because it's a lot of domain knowledge about distillery to understand.
3. That's an interesting problem, but I think this solution is specific to a deploy environment, and might be overwhelming in a quickstart guide. Again, requires more domain knowledge about Distillery, and I want this repo to be a starting point for simple apps that can be modified to fit the problems (like the one you encountered).

**Comment by yaychris** [comment]
RE: #2, the solution I arrived at loads the environment file at runtime. The secrets aren't required in the build environment. The `boot_check` file is basically your final, built app's executable, so all the commands you run through that will load the environment file (so, basically everything).

I'm with you on the added complexity of the Distillery plugin. I spent a lot of time on this when I set it up and this was the simplest way I found to load the secrets as environment variables at runtime. Deploying Elixir apps is just kinda hard *<|:'(

**Comment by dbernheisel** [comment]
fwiw

this snippet is no good:
```bash
for secret in "$RELEASE_ROOT_DIR"/env.prod; do
  export "$secret"
done
```

that overcomplicates it and doesn't always work. 
Much simpler

```bash
. "$RELEASE_ROOT_DIR"/env.prod
```

and doesn't leak into the environment.

**Comment by dbernheisel** [comment]
@yaychris cool, I misunderstood how that plugin works.  You think a good starting place would be this snippet? `. "$RELEASE_ROOT_DIR"/env.prod` in each command script?

--- edit
`$RELEASE_ROOT_DIR` is the wrong directory. Maybe hardcode it to `. /home/deploy/your_app/config/env.prod`

**Comment by yaychris** [comment]
I wasn't super clear in my explanation, I should've linked to the script the plugin changes, which is [this guy](https://github.com/C2CPII/audit-app/blob/master/rel/templates/boot_check.eex#L10-L14).

This file is a copy of the default `boot_check` that Distillery creates. The highlighted lines are what I added, which does exactly what you're describing. (I have the environment file outside of the app's directory because it's managed by Ansible and shared across deployments.)

It's been awhile since I worked on this and I don't remember exactly how a deployed Elixir app is set up or how the commands work. I do remember that this `boot_check` file is loaded before every command, which is why I source the config file there. You could put it wherever you want I suppose.

**Comment by dbernheisel** [comment]
@yaychris Nice! Check out #3 and see if that's a good way of handling it.  It's untested right now, but maybe that's a good way of handling it.

**Comment by zporter** [comment]
[This line](https://github.com/vigetlabs/elixir-deploy-quickstart/blob/master/nginx-config#L32) in the Nginx config should be `proxy_set_header Connection $connection_upgrade;`.  Was super happy to see websocket support included in that sample config 👏 

Nothing else stands out to me. I wouldn't mind running through it at some point. I might try to squeeze that in the week after next. Nice work!

**Comment by dbernheisel** [comment]
thanks!
